Repository arthurrgsampaio/Projeto-Avaliativo-Quiz-JS, pull requests merged in 2023-08, with the labels that each got.

#53 formatando data e colocando hora
  scripts/pessoas.js
  scripts/script.js
Labels: bug, enhancement

#54 updates no css
  index.html
  style/style-dark.css
  style/style.css
  style/var.css
Labels: bug, enhancement

#55 ajuste no dark-mode
  style/style-dark.css
Labels: enhancement

#57 fixed bugs
  scripts/script.js
Labels: bug, enhancement

#59 revert to dark-update
  scripts/script.js
Labels: bug

#60 pull da lógica das tabelas
  scripts/script.js
Labels: bug

#61 arrumado o bug do horário
  scripts/script.js
Labels: bug

#62 clean code
  index.html
  scripts/script.js
  style/style-dark.css
  style/style.css
  style/var.css
Labels: enhancement
