Repository arthurrgsampaio/Projeto-Avaliativo-Quiz-JS, pull requests merged in 2023-07, with the labels that each got.

#15 added-questions
  index.html
  scripts/artes.js
  scripts/entretenimento.js
  scripts/esportes.js
Labels: enhancement

#17 css initialize
  index.html
  style/style.css
  style/var.css
Labels: enhancement

#18 ajustes das cores da paleta
  style/var.css
Labels: enhancement

#19 início da criação da funcionalidade do botão iniciar.
  index.html
  scripts/script.js
Labels: enhancement

#20 if acrescentado
  index.html
  scripts/script.js
Labels: enhancement

#22 css2
  style/style.css
Labels: enhancement

#24 Css update
  index.html
  scripts/script.js
  style/style.css
  style/var.css
Labels: enhancement

#25 funcionalidade botao continuar
  scripts/script.js
Labels: enhancement

#26 funcionalidade btn
  scripts/script.js
Labels: enhancement

#27 Inicio da estilização dark mode.
  index.html
  scripts/script.js
  style/style-dark.css
Labels: enhancement

#32 updates no css e lógica do script
  scripts/script.js
  style/style-dark.css
  style/style.css
Labels: bug, enhancement

#34 Ajuste btns
  index.html
  scripts/script.js
  style/style-dark.css
  style/style.css
Labels: bug, enhancement

#35 funcionalidade para o timer
  index.html
  scripts/script.js
  style/style-dark.css
  style/style.css
Labels: enhancement

#36 bugs arrumados e alerta adicionado
  index.html
  scripts/script.js
  style/style.css
Labels: bug, enhancement

#37 Cssdark update
  scripts/artes.js
  scripts/script.js
  style/style-dark.css
  style/style.css
Labels: bug, enhancement

#38 salvando alguns dados do usuario
  scripts/script.js
Labels: bug, enhancement

#40 Início da estilização da tela de ranking
  index.html
  scripts/script.js
  style/style-dark.css
  style/style.css
  style/var.css
Labels: enhancement

#43 logica população da segunda tabela
  index.html
  scripts/script.js
  style/style.css
Labels: enhancement

#45 btnConcluir
  scripts/script.js
Labels: duplicate

#48 primeiraTabela
  index.html
  scripts/pessoas.js
  scripts/script.js
Labels: enhancement

#50 added date
  scripts/script.js
Labels: bug, enhancement
